cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@sdl//:sdl",
        "@sdl2wrapper//:sdl2wrapper",
    ],
    data = [
        "data/fonts/Vera.ttf",
        "data/wolftextures.png",
    ]
)

cc_binary(
    name = "raycaster",
    srcs = ["raycaster.cc"],
    deps = [
        "@sdl//:sdl",
        "@sdl2wrapper//:sdl2wrapper",
    ],
    data = [
        "data/fonts/Vera.ttf",
        "data/wolftextures.png",
    ]
)